func_first_part_model(
  death_rate             = runif(1),
  retirement_rate        = runif(1),
  excess_mortality       = runif(1),
  increased_relapse_1    = runif(1),
  increased_relapse_2    = runif(1),
  increased_relapse_3    = runif(1),
  increased_relapse_4    = runif(1),
  increased_relapse_5    = runif(1),
  mean_dur_chron         = runif(1),
  leavemodel             = runif(1),
  incidence_no_history   = runif(1),
  pmild                  = runif(1),
  pmoderate              = runif(1),
  psevere                = runif(1),
  mildrecovery           = runif(1),
  mildpartial            = runif(1),
  mildchronic            = runif(1),
  moderaterecovery       = runif(1),
  moderatepartial        = runif(1),
  moderatechronic        = runif(1),
  severerecovery         = runif(1),
  severepartial          = runif(1),
  severechronic          = runif(1),
  mildrecoverycured      = runif(1),
  mildrecoveryrelapse    = runif(1),
  mildpartialcured       = runif(1),
  mildpartialrelapse     = runif(1),
  moderaterecoveryrelapse= runif(1),
  moderaterecoverycured  = runif(1),
  moderatepartialcured   = runif(1),
  moderatepartialrelapse = runif(1),
  severerecoverycured    = runif(1),
  severerecoveryrelapse  = runif(1),
  severepartialcured     = runif(1),
  severepartialrelapse   = runif(1)
)

res
